// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: rpc/management.proto

package rpc

import (
	common "github.com/siderolabs/theila/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatusSpec_Phase int32

const (
	TaskStatusSpec_FAILED   TaskStatusSpec_Phase = 0
	TaskStatusSpec_RUNNING  TaskStatusSpec_Phase = 1
	TaskStatusSpec_COMPLETE TaskStatusSpec_Phase = 2
)

// Enum value maps for TaskStatusSpec_Phase.
var (
	TaskStatusSpec_Phase_name = map[int32]string{
		0: "FAILED",
		1: "RUNNING",
		2: "COMPLETE",
	}
	TaskStatusSpec_Phase_value = map[string]int32{
		"FAILED":   0,
		"RUNNING":  1,
		"COMPLETE": 2,
	}
)

func (x TaskStatusSpec_Phase) Enum() *TaskStatusSpec_Phase {
	p := new(TaskStatusSpec_Phase)
	*p = x
	return p
}

func (x TaskStatusSpec_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatusSpec_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_management_proto_enumTypes[0].Descriptor()
}

func (TaskStatusSpec_Phase) Type() protoreflect.EnumType {
	return &file_rpc_management_proto_enumTypes[0]
}

func (x TaskStatusSpec_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatusSpec_Phase.Descriptor instead.
func (TaskStatusSpec_Phase) EnumDescriptor() ([]byte, []int) {
	return file_rpc_management_proto_rawDescGZIP(), []int{3, 0}
}

type UpgradeInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// FromVersion is the lowest detected Kubernetes version.
	FromVersion string `protobuf:"bytes,1,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
}

func (x *UpgradeInfoResponse) Reset() {
	*x = UpgradeInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_management_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpgradeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeInfoResponse) ProtoMessage() {}

func (x *UpgradeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_management_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeInfoResponse.ProtoReflect.Descriptor instead.
func (*UpgradeInfoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_management_proto_rawDescGZIP(), []int{0}
}

func (x *UpgradeInfoResponse) GetFromVersion() string {
	if x != nil {
		return x.FromVersion
	}
	return ""
}

type UpgradeK8SSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// K8s version to upgrade from.
	FromVersion string `protobuf:"bytes,1,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	// K8s version to upgrade to.
	ToVersion string `protobuf:"bytes,2,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"`
	// Context to use.
	Context *common.Context `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
}

func (x *UpgradeK8SSpec) Reset() {
	*x = UpgradeK8SSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_management_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpgradeK8SSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeK8SSpec) ProtoMessage() {}

func (x *UpgradeK8SSpec) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_management_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeK8SSpec.ProtoReflect.Descriptor instead.
func (*UpgradeK8SSpec) Descriptor() ([]byte, []int) {
	return file_rpc_management_proto_rawDescGZIP(), []int{1}
}

func (x *UpgradeK8SSpec) GetFromVersion() string {
	if x != nil {
		return x.FromVersion
	}
	return ""
}

func (x *UpgradeK8SSpec) GetToVersion() string {
	if x != nil {
		return x.ToVersion
	}
	return ""
}

func (x *UpgradeK8SSpec) GetContext() *common.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

// Maps the task spec into task status spec.
type TaskStateSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// StatusID keeps the id for the current task status.
	StatusId string `protobuf:"bytes,4,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
}

func (x *TaskStateSpec) Reset() {
	*x = TaskStateSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_management_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskStateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStateSpec) ProtoMessage() {}

func (x *TaskStateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_management_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStateSpec.ProtoReflect.Descriptor instead.
func (*TaskStateSpec) Descriptor() ([]byte, []int) {
	return file_rpc_management_proto_rawDescGZIP(), []int{2}
}

func (x *TaskStateSpec) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

type TaskStatusSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Upgrade task state.
	Phase TaskStatusSpec_Phase `protobuf:"varint,1,opt,name=phase,proto3,enum=management.TaskStatusSpec_Phase" json:"phase,omitempty"`
	// Progress represents the task progress [0,1].
	Progress float32 `protobuf:"fixed32,2,opt,name=progress,proto3" json:"progress,omitempty"`
	// Failure reason.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// K8s version to upgrade from.
	FromVersion string `protobuf:"bytes,4,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	// K8s version to upgrade to.
	ToVersion string `protobuf:"bytes,5,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"`
	// FinishedAt is when the task either failed or completed.
	FinishedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
}

func (x *TaskStatusSpec) Reset() {
	*x = TaskStatusSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_management_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskStatusSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusSpec) ProtoMessage() {}

func (x *TaskStatusSpec) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_management_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusSpec.ProtoReflect.Descriptor instead.
func (*TaskStatusSpec) Descriptor() ([]byte, []int) {
	return file_rpc_management_proto_rawDescGZIP(), []int{3}
}

func (x *TaskStatusSpec) GetPhase() TaskStatusSpec_Phase {
	if x != nil {
		return x.Phase
	}
	return TaskStatusSpec_FAILED
}

func (x *TaskStatusSpec) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskStatusSpec) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskStatusSpec) GetFromVersion() string {
	if x != nil {
		return x.FromVersion
	}
	return ""
}

func (x *TaskStatusSpec) GetToVersion() string {
	if x != nil {
		return x.ToVersion
	}
	return ""
}

func (x *TaskStatusSpec) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type TaskLogSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Line represents a single log line.
	Line string `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
}

func (x *TaskLogSpec) Reset() {
	*x = TaskLogSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_management_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskLogSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogSpec) ProtoMessage() {}

func (x *TaskLogSpec) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_management_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogSpec.ProtoReflect.Descriptor instead.
func (*TaskLogSpec) Descriptor() ([]byte, []int) {
	return file_rpc_management_proto_rawDescGZIP(), []int{4}
}

func (x *TaskLogSpec) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type KubernetesVersionSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Version kubernetes version.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *KubernetesVersionSpec) Reset() {
	*x = KubernetesVersionSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_management_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubernetesVersionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesVersionSpec) ProtoMessage() {}

func (x *KubernetesVersionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_management_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesVersionSpec.ProtoReflect.Descriptor instead.
func (*KubernetesVersionSpec) Descriptor() ([]byte, []int) {
	return file_rpc_management_proto_rawDescGZIP(), []int{5}
}

func (x *KubernetesVersionSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_rpc_management_proto protoreflect.FileDescriptor

var file_rpc_management_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x68, 0x65, 0x69, 0x6c,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x13, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x7d, 0x0a, 0x0e, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x4b, 0x38, 0x73, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2c,
	0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x64, 0x22, 0xa9, 0x02, 0x0a,
	0x0e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x36, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65,
	0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f,
	0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x0b, 0x66,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2e, 0x0a, 0x05, 0x50, 0x68, 0x61, 0x73,
	0x65, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f,
	0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x22, 0x21, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b,
	0x4c, 0x6f, 0x67, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x31, 0x0a, 0x15, 0x4b,
	0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x53, 0x70, 0x65, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x5b,
	0x0a, 0x11, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1f, 0x2e, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x64, 0x65, 0x72, 0x6f,
	0x6c, 0x61, 0x62, 0x73, 0x2f, 0x74, 0x68, 0x65, 0x69, 0x6c, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_management_proto_rawDescOnce sync.Once
	file_rpc_management_proto_rawDescData = file_rpc_management_proto_rawDesc
)

func file_rpc_management_proto_rawDescGZIP() []byte {
	file_rpc_management_proto_rawDescOnce.Do(func() {
		file_rpc_management_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_management_proto_rawDescData)
	})
	return file_rpc_management_proto_rawDescData
}

var file_rpc_management_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_management_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_management_proto_goTypes = []interface{}{
	(TaskStatusSpec_Phase)(0),     // 0: management.TaskStatusSpec.Phase
	(*UpgradeInfoResponse)(nil),   // 1: management.UpgradeInfoResponse
	(*UpgradeK8SSpec)(nil),        // 2: management.UpgradeK8sSpec
	(*TaskStateSpec)(nil),         // 3: management.TaskStateSpec
	(*TaskStatusSpec)(nil),        // 4: management.TaskStatusSpec
	(*TaskLogSpec)(nil),           // 5: management.TaskLogSpec
	(*KubernetesVersionSpec)(nil), // 6: management.KubernetesVersionSpec
	(*common.Context)(nil),        // 7: common.Context
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_rpc_management_proto_depIdxs = []int32{
	7, // 0: management.UpgradeK8sSpec.context:type_name -> common.Context
	0, // 1: management.TaskStatusSpec.phase:type_name -> management.TaskStatusSpec.Phase
	8, // 2: management.TaskStatusSpec.finished_at:type_name -> google.protobuf.Timestamp
	9, // 3: management.ManagementService.UpgradeInfo:input_type -> google.protobuf.Empty
	1, // 4: management.ManagementService.UpgradeInfo:output_type -> management.UpgradeInfoResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_management_proto_init() }
func file_rpc_management_proto_init() {
	if File_rpc_management_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_management_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpgradeInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_management_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpgradeK8SSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_management_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskStateSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_management_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskStatusSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_management_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskLogSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_management_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KubernetesVersionSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_management_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_management_proto_goTypes,
		DependencyIndexes: file_rpc_management_proto_depIdxs,
		EnumInfos:         file_rpc_management_proto_enumTypes,
		MessageInfos:      file_rpc_management_proto_msgTypes,
	}.Build()
	File_rpc_management_proto = out.File
	file_rpc_management_proto_rawDesc = nil
	file_rpc_management_proto_goTypes = nil
	file_rpc_management_proto_depIdxs = nil
}
