// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: rpc/resource.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	resource "github.com/talos-systems/talos/pkg/machinery/api/resource"
	common "github.com/talos-systems/theila/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetFromClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *resource.GetRequest `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Context to use to get the resource.
	Context *common.Context `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	// Data source to use to get the resource.
	Source common.Source `protobuf:"varint,3,opt,name=source,proto3,enum=common.Source" json:"source,omitempty"`
}

func (x *GetFromClusterRequest) Reset() {
	*x = GetFromClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resource_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFromClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFromClusterRequest) ProtoMessage() {}

func (x *GetFromClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resource_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFromClusterRequest.ProtoReflect.Descriptor instead.
func (*GetFromClusterRequest) Descriptor() ([]byte, []int) {
	return file_rpc_resource_proto_rawDescGZIP(), []int{0}
}

func (x *GetFromClusterRequest) GetResource() *resource.GetRequest {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *GetFromClusterRequest) GetContext() *common.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetFromClusterRequest) GetSource() common.Source {
	if x != nil {
		return x.Source
	}
	return common.Source_Kubernetes
}

type GetFromClusterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Body should contain JSON encoded spec.
	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *GetFromClusterResponse) Reset() {
	*x = GetFromClusterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resource_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFromClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFromClusterResponse) ProtoMessage() {}

func (x *GetFromClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resource_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFromClusterResponse.ProtoReflect.Descriptor instead.
func (*GetFromClusterResponse) Descriptor() ([]byte, []int) {
	return file_rpc_resource_proto_rawDescGZIP(), []int{1}
}

func (x *GetFromClusterResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ListFromClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *resource.ListRequest `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Context to use to get the resource.
	Context *common.Context `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	// Data source to use to get the resource.
	Source common.Source `protobuf:"varint,3,opt,name=source,proto3,enum=common.Source" json:"source,omitempty"`
	// Selectors allow filtering list results by labels.
	Selectors []string `protobuf:"bytes,4,rep,name=selectors,proto3" json:"selectors,omitempty"`
}

func (x *ListFromClusterRequest) Reset() {
	*x = ListFromClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resource_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFromClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFromClusterRequest) ProtoMessage() {}

func (x *ListFromClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resource_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFromClusterRequest.ProtoReflect.Descriptor instead.
func (*ListFromClusterRequest) Descriptor() ([]byte, []int) {
	return file_rpc_resource_proto_rawDescGZIP(), []int{2}
}

func (x *ListFromClusterRequest) GetResource() *resource.ListRequest {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ListFromClusterRequest) GetContext() *common.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ListFromClusterRequest) GetSource() common.Source {
	if x != nil {
		return x.Source
	}
	return common.Source_Kubernetes
}

func (x *ListFromClusterRequest) GetSelectors() []string {
	if x != nil {
		return x.Selectors
	}
	return nil
}

type ListFromClusterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Messages should contain JSON encoded list spec.
	Messages []string `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *ListFromClusterResponse) Reset() {
	*x = ListFromClusterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resource_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFromClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFromClusterResponse) ProtoMessage() {}

func (x *ListFromClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resource_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFromClusterResponse.ProtoReflect.Descriptor instead.
func (*ListFromClusterResponse) Descriptor() ([]byte, []int) {
	return file_rpc_resource_proto_rawDescGZIP(), []int{3}
}

func (x *ListFromClusterResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Context to get the configuration from.
	Context *common.Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// Cluster to get the configuration for.
	Cluster *common.Cluster `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// Data source to use to get the resource.
	Source common.Source `protobuf:"varint,3,opt,name=source,proto3,enum=common.Source" json:"source,omitempty"`
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resource_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resource_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_rpc_resource_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigRequest) GetContext() *common.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ConfigRequest) GetCluster() *common.Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *ConfigRequest) GetSource() common.Source {
	if x != nil {
		return x.Source
	}
	return common.Source_Kubernetes
}

type ConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Data raw config data.
	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resource_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resource_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_rpc_resource_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_rpc_resource_proto protoreflect.FileDescriptor

var file_rpc_resource_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x1a, 0x1d,
	0x74, 0x61, 0x6c, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x68, 0x65, 0x69, 0x6c, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x9c, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x29,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x22, 0x2c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22,
	0xbc, 0x01, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x29, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x35,
	0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x29, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x26, 0x0a,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xef, 0x01, 0x0a, 0x16,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1f, 0x2e,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f,
	0x6d, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4b, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x17, 0x2e, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x29, 0x5a,
	0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x6c, 0x6f,
	0x73, 0x2d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x2f, 0x74, 0x68, 0x65, 0x69, 0x6c, 0x61,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_resource_proto_rawDescOnce sync.Once
	file_rpc_resource_proto_rawDescData = file_rpc_resource_proto_rawDesc
)

func file_rpc_resource_proto_rawDescGZIP() []byte {
	file_rpc_resource_proto_rawDescOnce.Do(func() {
		file_rpc_resource_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_resource_proto_rawDescData)
	})
	return file_rpc_resource_proto_rawDescData
}

var file_rpc_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_resource_proto_goTypes = []interface{}{
	(*GetFromClusterRequest)(nil),   // 0: resource.GetFromClusterRequest
	(*GetFromClusterResponse)(nil),  // 1: resource.GetFromClusterResponse
	(*ListFromClusterRequest)(nil),  // 2: resource.ListFromClusterRequest
	(*ListFromClusterResponse)(nil), // 3: resource.ListFromClusterResponse
	(*ConfigRequest)(nil),           // 4: resource.ConfigRequest
	(*ConfigResponse)(nil),          // 5: resource.ConfigResponse
	(*resource.GetRequest)(nil),     // 6: resource.GetRequest
	(*common.Context)(nil),          // 7: common.Context
	(common.Source)(0),              // 8: common.Source
	(*resource.ListRequest)(nil),    // 9: resource.ListRequest
	(*common.Cluster)(nil),          // 10: common.Cluster
}
var file_rpc_resource_proto_depIdxs = []int32{
	6,  // 0: resource.GetFromClusterRequest.resource:type_name -> resource.GetRequest
	7,  // 1: resource.GetFromClusterRequest.context:type_name -> common.Context
	8,  // 2: resource.GetFromClusterRequest.source:type_name -> common.Source
	9,  // 3: resource.ListFromClusterRequest.resource:type_name -> resource.ListRequest
	7,  // 4: resource.ListFromClusterRequest.context:type_name -> common.Context
	8,  // 5: resource.ListFromClusterRequest.source:type_name -> common.Source
	7,  // 6: resource.ConfigRequest.context:type_name -> common.Context
	10, // 7: resource.ConfigRequest.cluster:type_name -> common.Cluster
	8,  // 8: resource.ConfigRequest.source:type_name -> common.Source
	0,  // 9: resource.ClusterResourceService.Get:input_type -> resource.GetFromClusterRequest
	2,  // 10: resource.ClusterResourceService.List:input_type -> resource.ListFromClusterRequest
	4,  // 11: resource.ClusterResourceService.GetConfig:input_type -> resource.ConfigRequest
	1,  // 12: resource.ClusterResourceService.Get:output_type -> resource.GetFromClusterResponse
	3,  // 13: resource.ClusterResourceService.List:output_type -> resource.ListFromClusterResponse
	5,  // 14: resource.ClusterResourceService.GetConfig:output_type -> resource.ConfigResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_rpc_resource_proto_init() }
func file_rpc_resource_proto_init() {
	if File_rpc_resource_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_resource_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFromClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resource_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFromClusterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resource_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFromClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resource_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFromClusterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resource_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resource_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_resource_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_resource_proto_goTypes,
		DependencyIndexes: file_rpc_resource_proto_depIdxs,
		MessageInfos:      file_rpc_resource_proto_msgTypes,
	}.Build()
	File_rpc_resource_proto = out.File
	file_rpc_resource_proto_rawDesc = nil
	file_rpc_resource_proto_goTypes = nil
	file_rpc_resource_proto_depIdxs = nil
}
