// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.7
// source: socket/message/message.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	resource "github.com/talos-systems/talos/pkg/machinery/api/resource"
	common "github.com/talos-systems/theila/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Message kinds.
type Kind int32

const (
	Kind_Error           Kind = 0 // A generic error response.
	Kind_OK              Kind = 1 // A generic ok response.
	Kind_Watch           Kind = 2 // Watch request.
	Kind_Unsubscribe     Kind = 3 // Unsubscribe request.
	Kind_Subscribed      Kind = 4 // Subscribed response.
	Kind_EventItemAdd    Kind = 5 // Watch add item event.
	Kind_EventItemUpdate Kind = 6 // Watch update item event.
	Kind_EventItemDelete Kind = 7 // Watch delete item event.
	Kind_EventError      Kind = 8 // Watch error which means that watch is invalid.
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "Error",
		1: "OK",
		2: "Watch",
		3: "Unsubscribe",
		4: "Subscribed",
		5: "EventItemAdd",
		6: "EventItemUpdate",
		7: "EventItemDelete",
		8: "EventError",
	}
	Kind_value = map[string]int32{
		"Error":           0,
		"OK":              1,
		"Watch":           2,
		"Unsubscribe":     3,
		"Subscribed":      4,
		"EventItemAdd":    5,
		"EventItemUpdate": 6,
		"EventItemDelete": 7,
		"EventError":      8,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_socket_message_message_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_socket_message_message_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_socket_message_message_proto_rawDescGZIP(), []int{0}
}

// Message metadata which helps matching request vs response and routing to any specific subscription.
type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Uid match/route identifier.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socket_message_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_socket_message_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_socket_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// Web socket message.
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     Kind      `protobuf:"varint,1,opt,name=kind,proto3,enum=Kind" json:"kind,omitempty"`
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec can vary on the message kind.
	// Can either have some specific data for the kind or be empty.
	Spec string `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socket_message_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_socket_message_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_socket_message_message_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_Error
}

func (x *Message) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

type WatchSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Resource name to watch.
	Resource *resource.WatchRequest `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Source to get the watch data from.
	Source common.Runtime `protobuf:"varint,2,opt,name=source,proto3,enum=common.Runtime" json:"source,omitempty"`
	// Context settings to fetch the data from.
	Context *common.Context `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	// Selector represents watch label selector.
	Selector string `protobuf:"bytes,4,opt,name=selector,proto3" json:"selector,omitempty"`
}

func (x *WatchSpec) Reset() {
	*x = WatchSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socket_message_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSpec) ProtoMessage() {}

func (x *WatchSpec) ProtoReflect() protoreflect.Message {
	mi := &file_socket_message_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSpec.ProtoReflect.Descriptor instead.
func (*WatchSpec) Descriptor() ([]byte, []int) {
	return file_socket_message_message_proto_rawDescGZIP(), []int{2}
}

func (x *WatchSpec) GetResource() *resource.WatchRequest {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *WatchSpec) GetSource() common.Runtime {
	if x != nil {
		return x.Source
	}
	return common.Runtime_Kubernetes
}

func (x *WatchSpec) GetContext() *common.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *WatchSpec) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

// Watch response.
type SubscribedSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Subscription uid generated for the subscription.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *SubscribedSpec) Reset() {
	*x = SubscribedSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socket_message_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribedSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribedSpec) ProtoMessage() {}

func (x *SubscribedSpec) ProtoReflect() protoreflect.Message {
	mi := &file_socket_message_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribedSpec.ProtoReflect.Descriptor instead.
func (*SubscribedSpec) Descriptor() ([]byte, []int) {
	return file_socket_message_message_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribedSpec) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// Unsubscribe request.
type UnsubscribeSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Subscription to destroy.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UnsubscribeSpec) Reset() {
	*x = UnsubscribeSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socket_message_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsubscribeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeSpec) ProtoMessage() {}

func (x *UnsubscribeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_socket_message_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeSpec.ProtoReflect.Descriptor instead.
func (*UnsubscribeSpec) Descriptor() ([]byte, []int) {
	return file_socket_message_message_proto_rawDescGZIP(), []int{4}
}

func (x *UnsubscribeSpec) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ErrorSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ErrorSpec) Reset() {
	*x = ErrorSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socket_message_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorSpec) ProtoMessage() {}

func (x *ErrorSpec) ProtoReflect() protoreflect.Message {
	mi := &file_socket_message_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorSpec.ProtoReflect.Descriptor instead.
func (*ErrorSpec) Descriptor() ([]byte, []int) {
	return file_socket_message_message_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorSpec) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ItemUpdateSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Old []byte `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New []byte `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
}

func (x *ItemUpdateSpec) Reset() {
	*x = ItemUpdateSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socket_message_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemUpdateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUpdateSpec) ProtoMessage() {}

func (x *ItemUpdateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_socket_message_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUpdateSpec.ProtoReflect.Descriptor instead.
func (*ItemUpdateSpec) Descriptor() ([]byte, []int) {
	return file_socket_message_message_proto_rawDescGZIP(), []int{6}
}

func (x *ItemUpdateSpec) GetOld() []byte {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *ItemUpdateSpec) GetNew() []byte {
	if x != nil {
		return x.New
	}
	return nil
}

var File_socket_message_message_proto protoreflect.FileDescriptor

var file_socket_message_message_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x68, 0x65, 0x69, 0x6c, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x74, 0x61, 0x6c, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x22, 0x5f, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x4b, 0x69, 0x6e, 0x64,
	0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x70, 0x65,
	0x63, 0x22, 0xaf, 0x01, 0x0a, 0x09, 0x57, 0x61, 0x74, 0x63, 0x68, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x32, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x22, 0x22, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x64, 0x53, 0x70, 0x65, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x0f, 0x55, 0x6e, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x09,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x70, 0x65, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x34, 0x0a, 0x0e, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6f, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6e, 0x65, 0x77, 0x2a, 0x91, 0x01, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b,
	0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x10, 0x03, 0x12, 0x0e, 0x0a,
	0x0a, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x10, 0x04, 0x12, 0x10, 0x0a,
	0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x41, 0x64, 0x64, 0x10, 0x05, 0x12,
	0x13, 0x0a, 0x0f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x10, 0x06, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x08, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_socket_message_message_proto_rawDescOnce sync.Once
	file_socket_message_message_proto_rawDescData = file_socket_message_message_proto_rawDesc
)

func file_socket_message_message_proto_rawDescGZIP() []byte {
	file_socket_message_message_proto_rawDescOnce.Do(func() {
		file_socket_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_socket_message_message_proto_rawDescData)
	})
	return file_socket_message_message_proto_rawDescData
}

var file_socket_message_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_socket_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_socket_message_message_proto_goTypes = []interface{}{
	(Kind)(0),                     // 0: Kind
	(*Metadata)(nil),              // 1: Metadata
	(*Message)(nil),               // 2: Message
	(*WatchSpec)(nil),             // 3: WatchSpec
	(*SubscribedSpec)(nil),        // 4: SubscribedSpec
	(*UnsubscribeSpec)(nil),       // 5: UnsubscribeSpec
	(*ErrorSpec)(nil),             // 6: ErrorSpec
	(*ItemUpdateSpec)(nil),        // 7: ItemUpdateSpec
	(*resource.WatchRequest)(nil), // 8: resource.WatchRequest
	(common.Runtime)(0),           // 9: common.Runtime
	(*common.Context)(nil),        // 10: common.Context
}
var file_socket_message_message_proto_depIdxs = []int32{
	0,  // 0: Message.kind:type_name -> Kind
	1,  // 1: Message.metadata:type_name -> Metadata
	8,  // 2: WatchSpec.resource:type_name -> resource.WatchRequest
	9,  // 3: WatchSpec.source:type_name -> common.Runtime
	10, // 4: WatchSpec.context:type_name -> common.Context
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_socket_message_message_proto_init() }
func file_socket_message_message_proto_init() {
	if File_socket_message_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_socket_message_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socket_message_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socket_message_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socket_message_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribedSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socket_message_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsubscribeSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socket_message_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socket_message_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemUpdateSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_socket_message_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_socket_message_message_proto_goTypes,
		DependencyIndexes: file_socket_message_message_proto_depIdxs,
		EnumInfos:         file_socket_message_message_proto_enumTypes,
		MessageInfos:      file_socket_message_message_proto_msgTypes,
	}.Build()
	File_socket_message_message_proto = out.File
	file_socket_message_message_proto_rawDesc = nil
	file_socket_message_message_proto_goTypes = nil
	file_socket_message_message_proto_depIdxs = nil
}
